### ISSUE TITLE
MSA, Kafka 도입 여부 결정

### ISSUE THREAD

**Issue by pigggulggul** [kong-dak/kong-dak#10]

**Comment by Changho0514** [comment]
- 몇명의 사용자를 기대하는지(동시 접속자수, MAU)
  - MAU 1,000
  - DAU 500
  - 동접 최대 50

**Comment by Changho0514** [comment]
# MSA 도입 검토 결과
현재는 모놀리식 구조 선택, 추후 MSA 전환 가능성 고려

## 결정 이유

### 1. 초기 서비스에 적합한 모놀리식 구조
- 현재 예상 트래픽은 단일 서버로 충분한 처리 가능
- 개발 리소스를 비즈니스 로직 구현에 집중 가능
- 초기 운영 비용 절감 효과

### 2. 점진적 분리 전략 채택
- 실제 사용자 패턴과 부하 지점 파악 후 효율적 분리
- 데이터 정합성 이슈를 초기에 방지
- 불필요한 분산 시스템 복잡도 회피

### 3. 기술적 준비 필요
- 도메인 경계가 명확하지 않은 현 상태
- DDD, EDA에 대한 추가 학습 필요
- 팀 전체의 MSA 이해도 향상 필요

## 향후 방향성

### 1. 성능 모니터링 체계 구축
- 병목 구간 식별을 위한 모니터링 시스템 구축
- 트래픽 패턴 분석 및 추적

### 2. 단계적 기술 역량 확보
- DDD 스터디 및 도메인별 설계 패턴 적용
- 이벤트 기반 아키텍처 점진적 도입
- 분산 시스템 관련 기술 학습

### 3. MSA 전환 기준 수립
- 트래픽 임계점 설정
- 도메인별 독립 배포 필요성 모니터링
- 성장 단계별 전환 계획 수립

---
Note: 현재는 모놀리식으로 시작하되, 확장 가능한 구조로 설계하여 향후 MSA 전환에 대비하겠습니다.
